{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.own.owntv",
    "module": "core",
    "version": "1.0.66",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.66.aar",
          "url": "core-1.0.66.aar",
          "size": 8402248,
          "sha512": "2a701c0c94956dd3ffb9131b0c6e8e9d6bf28f4fc1c1594e6ab3d9d2c1a4b698617d1294ce31650bf3a1b3df5cc047e8477991523e55b5d1f50f0dc13ebad811",
          "sha256": "ba71f3d97a591136cfc9b5dd20639b35e63e55a59cf922a30046365a5ccc6967",
          "sha1": "ee04ec94c4a261704d646495eea2b5b9121d631e",
          "md5": "c0f36f207e7dfcb15f2317c281a04c63"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.2"
          }
        },
        {
          "group": "androidx.tvprovider",
          "module": "tvprovider",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.github.albfernandez",
          "module": "juniversalchardet",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.2.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android"
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.08.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.66.aar",
          "url": "core-1.0.66.aar",
          "size": 8402248,
          "sha512": "2a701c0c94956dd3ffb9131b0c6e8e9d6bf28f4fc1c1594e6ab3d9d2c1a4b698617d1294ce31650bf3a1b3df5cc047e8477991523e55b5d1f50f0dc13ebad811",
          "sha256": "ba71f3d97a591136cfc9b5dd20639b35e63e55a59cf922a30046365a5ccc6967",
          "sha1": "ee04ec94c4a261704d646495eea2b5b9121d631e",
          "md5": "c0f36f207e7dfcb15f2317c281a04c63"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.0.66-sources.jar",
          "url": "core-1.0.66-sources.jar",
          "size": 1005820,
          "sha512": "b30d39ec53f5b812ce7e3defc07db901be2b1714fd07c38441e391701ee3913a4216c01fe4c21c127888e980416db27ab9dd8e3b0360a065d31bc5bff8643c4a",
          "sha256": "609a5b5e2f9cac0bd0ac169d337983649f58dd90e1d4f1926adc144d5ff6466b",
          "sha1": "6748de1da83868b5739e4326f534f855ec400e70",
          "md5": "2b40a570a1074de01a6c61771b6e6a5d"
        }
      ]
    }
  ]
}
