{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.own.owntv",
    "module": "libmpv",
    "version": "2026.10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "libmpv-2026.10.2.aar",
          "url": "libmpv-2026.10.2.aar",
          "size": 36345625,
          "sha512": "d1f05d3868182a08d76d33b465d292d72057a7695e77b8a36f9c418b02d8cfccadf9d1c2d11b94e77ac0f580fd3875f06165d925a7856c478a5a39ad897f9eec",
          "sha256": "166696341e6d7ef4c75c34f5acc41d284c1c3da80123a0a92d3350b5e2ba67f4",
          "sha1": "840a92a8b47adf3d93cd0a4aaaa0a3d1eec49080",
          "md5": "c365192162ab8a65135990fb2216e5c1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "libmpv-2026.10.2.aar",
          "url": "libmpv-2026.10.2.aar",
          "size": 36345625,
          "sha512": "d1f05d3868182a08d76d33b465d292d72057a7695e77b8a36f9c418b02d8cfccadf9d1c2d11b94e77ac0f580fd3875f06165d925a7856c478a5a39ad897f9eec",
          "sha256": "166696341e6d7ef4c75c34f5acc41d284c1c3da80123a0a92d3350b5e2ba67f4",
          "sha1": "840a92a8b47adf3d93cd0a4aaaa0a3d1eec49080",
          "md5": "c365192162ab8a65135990fb2216e5c1"
        }
      ]
    }
  ]
}
